# Fichier pyproject.toml à la racine de votre projet

[tool.ruff]
# Vise la compatibilité avec Python 3.9+
target-version = "py39"

# Règles de linting à appliquer. 'E' et 'F' sont les règles de base (pycodestyle, pyflakes)
select = ["E", "F", "W", "I"]

# Ignore certaines règles si nécessaire. Par exemple, E501 pour la longueur de ligne
ignore = ["E501"]

# Exclut les dossiers qui ne doivent pas être analysés
exclude = [
    ".git",
    ".github",
EOM
 [
    ".git",
    ".github",
EOM
