# Configuration principale pour Ruff
[tool.ruff]
target-version = "py39"
exclude = [
    ".git",
    ".github",
    ".venv",
    "__pycache__",
]

# Section spécifique pour les règles du Linter
[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]

# Section spécifique pour les règles du Formateur
[tool.ruff.format]
quote-style = "double"
