blank_issues_enabled: false
contact_links:
  - name: "📄 Documentation / Documentation"
    url: "https://github.com/CharlesP44/Beem_Energy#readme"
    about: "Consultez la documentation avant de créer une issue. / Check the documentation before creating an issue."
