name: HassFest Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hassfest:
    name: HassFest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HassFest
        uses: home-assistant/actions/hassfest@master
